name: Generate README.md

on:
  push:
    branches:
      - develop
    paths:
    - 'README.template.md'
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    name: generate-readme
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
      - name: Generate access counter
        run: |
          git fetch --all
          git checkout readme-showcase
          git merge --ff-only master
          cat README.template.md | sed -e "s/<RANDOM_ACCESS_COUNTER_SEED>/${{ steps.generate-uuid.outputs.uuid }}/g" > README.md
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: Generate README.md
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            
