name: Generate README.md

on:
  push:
    paths:
    - 'README.template.md'
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:


jobs:
  generate_readme:
    runs-on: ubuntu-latest
    name: generate-readme
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
      - uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<RANDOM_ACCESS_COUNTER_SEED>"
          replace: ${{ steps.generate-uuid.outputs.uuid }}
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: Generate 3d contrib
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            
